const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const prefs={lang:localStorage.getItem('lang')||'es',theme:localStorage.getItem('theme')||'light'};
if(prefs.theme==='dark')document.body.classList.add('dark');

const UI_TRANSLATIONS={
 en:{
  'Inicio':'Home','Academia':'Academy','Simuladores':'Simulators','Prompts IA':'AI Prompts','FAQ':'FAQ','Empleo':'Jobs','Pago':'Payment','Iniciar sesión':'Sign in','Accesibilidad':'Accessibility','Aumentar texto':'Increase text','Disminuir texto':'Decrease text','Alto contraste':'High contrast','Subrayar enlaces':'Underline links','Reducir movimiento':'Reduce motion','Restablecer':'Reset','Saltar al contenido':'Skip to content',
  'Aprendizaje guiado':'Guided learning','Rutas':'Paths','Certificaciones':'Certifications','QA por industria':'QA by industry','Biblioteca':'Library','Learning Paths':'Learning Paths','Rutas recomendadas':'Recommended paths','Preparación ISTQB y AICS':'ISTQB and AICS preparation','Ir a simuladores':'Go to simulators','Cursos técnicos dentro de la Academia':'Technical courses in the Academy','Herramientas y práctica':'Tools and practice','Career Paths':'Career Paths','Biblioteca QA':'QA Library','Ebooks y revistas digitales':'Ebooks and digital magazines','Ebooks y libros abiertos':'Ebooks and open books','Revistas y publicaciones':'Magazines and publications','Preparación complementaria':'Additional preparation','Videos, preguntas explicadas y recursos gratuitos':'Videos, explained questions and free resources',
  'Practice lab':'Practice lab','Simulador por certificación':'Certification simulator','¿Listo para practicar?':'Ready to practice?','Pulse iniciar para elegir certificación, dificultad y nombre.':'Press start to choose certification, difficulty and name.','Iniciar prueba':'Start test','Configure su práctica':'Configure your practice','Certificación':'Certification','Dificultad':'Difficulty','Nombre para resultado/certificado':'Name for result/certificate','Comenzar 40 preguntas':'Start 40 questions','Material oficial ↗':'Official material ↗','Información AICS ↗':'AICS information ↗','Siguiente':'Next','Práctica completada':'Practice completed','Certificado PDF de aprovechamiento':'Completion PDF certificate','Nueva práctica':'New practice','Preparación:':'Preparation:',
  'Inscripción a la Academia':'Academy enrollment','Pago del curso':'Course payment','Cada curso corto tiene un valor de US$5.00. Se calcula IVA del 13% antes de mostrar el total.':'Each short course costs US$5.00. A 13% VAT is calculated before showing the total.','Catálogo de cursos':'Course catalog','Buscar curso…':'Search course…','Agregar seleccionados':'Add selected','Agregar todos los visibles':'Add all visible','Seleccionados':'Selected','Quitar seleccionados':'Remove selected','Vaciar selección':'Clear selection','Datos de tarjeta':'Card details','Nombre del titular':'Cardholder name','Número de tarjeta':'Card number','Vencimiento':'Expiry','Continuar pago':'Continue payment','Pagar con PayPal':'Pay with PayPal','Resumen':'Summary','Cursos seleccionados':'Selected courses','Subtotal':'Subtotal','IVA 13%':'VAT 13%','Total':'Total','Volver a Academia':'Back to Academy',
  'Todos los niveles':'All levels','Dificultad':'Difficulty','Todas las categorías':'All categories','Buscar certificación, tema o código…':'Search certification, topic or code…','Buscar herramienta o curso…':'Search tool or course…','Practicar':'Practice','Fuente oficial ↗':'Official source ↗','Abrir recurso ↗':'Open resource ↗','Referencia ↗':'Reference ↗','Recurso externo ↗':'External resource ↗','Gratis':'Free','Abrir gratis ↗':'Open free ↗','Abrir Virtuoso Training ↗':'Open Virtuoso Training ↗',
  'Tipo de certificación':'Certification scheme','ISTQB':'ISTQB','AICS':'AICS','Principiante · sin cronómetro':'Beginner · no timer','Fácil · 60 minutos':'Easy · 60 minutes','Medio · 45 minutos':'Medium · 45 minutes','Difícil · 30 minutos':'Hard · 30 minutes','Sin cronómetro':'No timer'
 },
 pt:{
  'Inicio':'Início','Academia':'Academia','Simuladores':'Simuladores','Prompts IA':'Prompts de IA','FAQ':'FAQ','Empleo':'Empregos','Pago':'Pagamento','Iniciar sesión':'Entrar','Accesibilidad':'Acessibilidade','Aumentar texto':'Aumentar texto','Disminuir texto':'Diminuir texto','Alto contraste':'Alto contraste','Subrayar enlaces':'Sublinhar links','Reducir movimiento':'Reduzir movimento','Restablecer':'Restaurar','Saltar al contenido':'Pular para o conteúdo',
  'Aprendizaje guiado':'Aprendizagem guiada','Rutas':'Trilhas','Certificaciones':'Certificações','QA por industria':'QA por setor','Biblioteca':'Biblioteca','Rutas recomendadas':'Trilhas recomendadas','Preparación ISTQB y AICS':'Preparação ISTQB e AICS','Ir a simuladores':'Ir aos simuladores','Cursos técnicos dentro de la Academia':'Cursos técnicos na Academia','Herramientas y práctica':'Ferramentas e prática','Biblioteca QA':'Biblioteca QA','Ebooks y revistas digitales':'Ebooks e revistas digitais','Ebooks y libros abiertos':'Ebooks e livros abertos','Revistas y publicaciones':'Revistas e publicações','Preparación complementaria':'Preparação complementar','Videos, preguntas explicadas y recursos gratuitos':'Vídeos, perguntas explicadas e recursos gratuitos',
  'Simulador por certificación':'Simulador por certificação','¿Listo para practicar?':'Pronto para praticar?','Pulse iniciar para elegir certificación, dificultad y nombre.':'Clique em iniciar para escolher certificação, dificuldade e nome.','Iniciar prueba':'Iniciar prova','Configure su práctica':'Configure sua prática','Certificación':'Certificação','Dificultad':'Dificuldade','Nombre para resultado/certificado':'Nome para resultado/certificado','Comenzar 40 preguntas':'Começar 40 perguntas','Material oficial ↗':'Material oficial ↗','Información AICS ↗':'Informação AICS ↗','Siguiente':'Próxima','Práctica completada':'Prática concluída','Nueva práctica':'Nova prática','Sin cronómetro':'Sem cronômetro',
  'Pago del curso':'Pagamento do curso','Catálogo de cursos':'Catálogo de cursos','Buscar curso…':'Buscar curso…','Agregar seleccionados':'Adicionar selecionados','Agregar todos los visibles':'Adicionar todos visíveis','Seleccionados':'Selecionados','Quitar seleccionados':'Remover selecionados','Vaciar selección':'Limpar seleção','Datos de tarjeta':'Dados do cartão','Nombre del titular':'Nome do titular','Número de tarjeta':'Número do cartão','Vencimiento':'Validade','Continuar pago':'Continuar pagamento','Pagar con PayPal':'Pagar com PayPal','Cursos seleccionados':'Cursos selecionados','Subtotal':'Subtotal','IVA 13%':'IVA 13%','Total':'Total','Volver a Academia':'Voltar à Academia',
  'Tipo de certificación':'Tipo de certificação','Principiante · sin cronómetro':'Iniciante · sem cronômetro','Fácil · 60 minutos':'Fácil · 60 minutos','Medio · 45 minutos':'Médio · 45 minutos','Difícil · 30 minutos':'Difícil · 30 minutos','Abrir gratis ↗':'Abrir grátis ↗','Abrir Virtuoso Training ↗':'Abrir Virtuoso Training ↗'
 },
 zh:{
  'Inicio':'首页','Academia':'学习中心','Simuladores':'模拟考试','Prompts IA':'AI 提示词','FAQ':'常见问题','Empleo':'工作','Pago':'付款','Iniciar sesión':'登录','Accesibilidad':'无障碍','Aumentar texto':'放大文字','Disminuir texto':'缩小文字','Alto contraste':'高对比度','Subrayar enlaces':'链接下划线','Reducir movimiento':'减少动画','Restablecer':'重置','Saltar al contenido':'跳到内容',
  'Rutas':'学习路径','Certificaciones':'认证','QA por industria':'行业 QA','Biblioteca':'资料库','Rutas recomendadas':'推荐学习路径','Preparación ISTQB y AICS':'ISTQB 与 AICS 备考','Ir a simuladores':'前往模拟考试','Cursos técnicos dentro de la Academia':'学习中心技术课程','Herramientas y práctica':'工具与实践','Biblioteca QA':'QA 资料库','Ebooks y revistas digitales':'电子书与数字期刊','Ebooks y libros abiertos':'电子书与开放图书','Revistas y publicaciones':'期刊与出版物','Preparación complementaria':'补充备考','Videos, preguntas explicadas y recursos gratuitos':'视频、题目讲解与免费资源',
  'Simulador por certificación':'认证模拟考试','¿Listo para practicar?':'准备练习了吗？','Iniciar prueba':'开始测试','Configure su práctica':'设置练习','Certificación':'认证','Dificultad':'难度','Nombre para resultado/certificado':'成绩/证书姓名','Comenzar 40 preguntas':'开始 40 题','Siguiente':'下一题','Práctica completada':'练习完成','Nueva práctica':'新的练习','Sin cronómetro':'不计时','Tipo de certificación':'认证体系','Principiante · sin cronómetro':'入门 · 不计时','Fácil · 60 minutos':'简单 · 60 分钟','Medio · 45 minutos':'中等 · 45 分钟','Difícil · 30 minutos':'困难 · 30 分钟',
  'Pago del curso':'课程付款','Catálogo de cursos':'课程目录','Buscar curso…':'搜索课程…','Agregar seleccionados':'添加所选','Agregar todos los visibles':'添加全部可见','Seleccionados':'已选择','Quitar seleccionados':'移除所选','Vaciar selección':'清空选择','Datos de tarjeta':'银行卡信息','Continuar pago':'继续付款','Pagar con PayPal':'使用 PayPal','Cursos seleccionados':'已选课程','Subtotal':'小计','IVA 13%':'增值税 13%','Total':'合计','Volver a Academia':'返回学习中心','Abrir gratis ↗':'免费打开 ↗','Abrir Virtuoso Training ↗':'打开 Virtuoso Training ↗'
 },
 hi:{
  'Inicio':'होम','Academia':'अकादमी','Simuladores':'सिमुलेटर','Prompts IA':'AI प्रॉम्प्ट','FAQ':'सामान्य प्रश्न','Empleo':'नौकरियाँ','Pago':'भुगतान','Iniciar sesión':'साइन इन','Accesibilidad':'सुलभता','Aumentar texto':'टेक्स्ट बढ़ाएँ','Disminuir texto':'टेक्स्ट घटाएँ','Alto contraste':'हाई कॉन्ट्रास्ट','Subrayar enlaces':'लिंक रेखांकित करें','Reducir movimiento':'एनीमेशन कम करें','Restablecer':'रीसेट','Saltar al contenido':'मुख्य सामग्री पर जाएँ',
  'Rutas':'लर्निंग पाथ','Certificaciones':'प्रमाणन','QA por industria':'उद्योग अनुसार QA','Biblioteca':'लाइब्रेरी','Rutas recomendadas':'अनुशंसित पाथ','Preparación ISTQB y AICS':'ISTQB और AICS तैयारी','Ir a simuladores':'सिमुलेटर पर जाएँ','Cursos técnicos dentro de la Academia':'अकादमी के तकनीकी कोर्स','Herramientas y práctica':'टूल और अभ्यास','Biblioteca QA':'QA लाइब्रेरी','Ebooks y revistas digitales':'ईबुक और डिजिटल पत्रिकाएँ','Preparación complementaria':'अतिरिक्त तैयारी',
  'Simulador por certificación':'प्रमाणन सिमुलेटर','¿Listo para practicar?':'अभ्यास के लिए तैयार?','Iniciar prueba':'टेस्ट शुरू करें','Configure su práctica':'अभ्यास सेट करें','Certificación':'प्रमाणन','Dificultad':'कठिनाई','Nombre para resultado/certificado':'परिणाम/प्रमाणपत्र के लिए नाम','Comenzar 40 preguntas':'40 प्रश्न शुरू करें','Siguiente':'अगला','Práctica completada':'अभ्यास पूरा हुआ','Nueva práctica':'नया अभ्यास','Sin cronómetro':'बिना टाइमर','Tipo de certificación':'प्रमाणन प्रकार','Principiante · sin cronómetro':'शुरुआती · बिना टाइमर','Fácil · 60 minutos':'आसान · 60 मिनट','Medio · 45 minutos':'मध्यम · 45 मिनट','Difícil · 30 minutos':'कठिन · 30 मिनट',
  'Pago del curso':'कोर्स भुगतान','Catálogo de cursos':'कोर्स सूची','Buscar curso…':'कोर्स खोजें…','Agregar seleccionados':'चयनित जोड़ें','Agregar todos los visibles':'सभी दिख रहे जोड़ें','Seleccionados':'चयनित','Quitar seleccionados':'चयनित हटाएँ','Vaciar selección':'चयन साफ़ करें','Datos de tarjeta':'कार्ड विवरण','Continuar pago':'भुगतान जारी रखें','Pagar con PayPal':'PayPal से भुगतान','Cursos seleccionados':'चयनित कोर्स','Subtotal':'उप-योग','IVA 13%':'कर 13%','Total':'कुल','Volver a Academia':'अकादमी पर वापस','Abrir gratis ↗':'मुफ़्त खोलें ↗','Abrir Virtuoso Training ↗':'Virtuoso Training खोलें ↗'
 }
};
function translateString(source,lang){if(lang==='es')return source;return (window.DATA_TRANSLATIONS?.[lang]?.[source])||(UI_TRANSLATIONS[lang]&&UI_TRANSLATIONS[lang][source])||source;}
function applyTranslations(lang=localStorage.getItem('lang')||'es',root=document){
 document.documentElement.lang=lang;
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.parentElement||['SCRIPT','STYLE','NOSCRIPT'].includes(n.parentElement.tagName))return NodeFilter.FILTER_REJECT;return n.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;}});
 const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 nodes.forEach(n=>{if(n.__i18nSource===undefined)n.__i18nSource=n.nodeValue;const raw=n.__i18nSource,trim=raw.trim(),lead=raw.slice(0,raw.indexOf(trim)),trail=raw.slice(raw.indexOf(trim)+trim.length);n.nodeValue=lead+translateString(trim,lang)+trail;});
 $$('input[placeholder],textarea[placeholder]',root).forEach(el=>{if(!el.dataset.i18nPlaceholder)el.dataset.i18nPlaceholder=el.placeholder;el.placeholder=translateString(el.dataset.i18nPlaceholder,lang)});
 $$('[aria-label]',root).forEach(el=>{if(!el.dataset.i18nAria)el.dataset.i18nAria=el.getAttribute('aria-label');el.setAttribute('aria-label',translateString(el.dataset.i18nAria,lang))});
 const sel=$('#language');if(sel)sel.value=lang;
}
window.applyTranslations=applyTranslations;window.t=(s)=>translateString(s,localStorage.getItem('lang')||'es');
const langSelect=$('#language');if(langSelect){langSelect.value=prefs.lang;langSelect.addEventListener('change',e=>{localStorage.setItem('lang',e.target.value);applyTranslations(e.target.value);window.dispatchEvent(new CustomEvent('languagechange',{detail:{lang:e.target.value}}));});}
applyTranslations(prefs.lang);

$('#themeToggle') && ($('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')});
$('#menuToggle') && ($('#menuToggle').onclick=()=>{const o=$('#mainNav').classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',String(o));});
$$('#mainNav a').forEach(a=>a.onclick=()=>$('#mainNav').classList.remove('open'));
$('#accessibilityToggle') && ($('#accessibilityToggle').onclick=()=>$('#accessibilityPanel').hidden=!$('#accessibilityPanel').hidden);
$('#closeAccessibility') && ($('#closeAccessibility').onclick=()=>$('#accessibilityPanel').hidden=true);
$$('[data-a11y]').forEach(b=>b.onclick=()=>{const a=b.dataset.a11y;if(a==='font+')document.documentElement.style.fontSize=(parseFloat(getComputedStyle(document.documentElement).fontSize)+1)+'px';if(a==='font-')document.documentElement.style.fontSize=Math.max(13,parseFloat(getComputedStyle(document.documentElement).fontSize)-1)+'px';if(a==='contrast')document.body.classList.toggle('high-contrast');if(a==='links')document.body.classList.toggle('links-underlined');if(a==='motion')document.body.classList.toggle('reduce-motion');if(a==='reset'){document.documentElement.style.fontSize='';document.body.classList.remove('high-contrast','links-underlined','reduce-motion')}});
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function slug(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase();}
function downloadSimplePdf(filename,lines){const esc=s=>String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?');let y=760,content='BT /F1 20 Tf 72 '+y+' Td ('+esc(lines[0]||'')+') Tj ET\n';y-=48;for(const line of lines.slice(1)){content+=`BT /F1 12 Tf 72 ${y} Td (${esc(line)}) Tj ET\n`;y-=28;}const objs=[];objs[1]='<< /Type /Catalog /Pages 2 0 R >>';objs[2]='<< /Type /Pages /Kids [3 0 R] /Count 1 >>';objs[3]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>';objs[4]=`<< /Length ${content.length} >>\nstream\n${content}endstream`;objs[5]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';let pdf='%PDF-1.4\n',offs=[0];for(let i=1;i<=5;i++){offs[i]=pdf.length;pdf+=`${i} 0 obj\n${objs[i]}\nendobj\n`;}const xref=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n';for(let i=1;i<=5;i++)pdf+=String(offs[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer << /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const blob=new Blob([pdf],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}


function downloadStyledCertificatePdf(filename,data){
  const latin=s=>String(s||'').replace(/[\()]/g,m=>'\\'+m).replace(/[^\x20-\x7E\xA0-\xFF]/g,'?').split('').map(ch=>{const c=ch.charCodeAt(0);return c>126?'\\'+c.toString(8).padStart(3,'0'):ch;}).join('');
  const center=(text,y,size=20,font='F1')=>{const approx=Math.min(700,String(text).length*size*.5);const x=Math.max(45,(792-approx)/2);return `BT /${font} ${size} Tf ${x.toFixed(1)} ${y} Td (${latin(text)}) Tj ET\n`;};
  const now=data.date instanceof Date?data.date:new Date(data.date||Date.now());
  const date=now.toLocaleDateString('es-CR',{year:'numeric',month:'long',day:'numeric'});
  let c='';
  c+='0.965 0.975 0.99 rg 0 0 792 612 re f\n';
  c+='0.08 0.32 0.58 rg 0 545 792 67 re f\n';
  c+='0.11 0.42 0.70 rg 0 0 500 48 re f\n';
  c+='0.90 0.93 0.97 rg 650 65 180 180 re f\n';
  c+='0.82 0.87 0.94 RG 7 w 620 110 120 120 re S\n';
  c+='0.08 0.20 0.35 rg BT /F2 24 Tf 40 565 Td (QA LEARNING HUB) Tj ET\n';
  c+='0.08 0.20 0.35 rg BT /F1 11 Tf 40 548 Td (Testing - Quality Engineering) Tj ET\n';
  c+='0.12 0.18 0.28 rg '+center(data.title||'Certificado de aprovechamiento',475,24,'F2');
  c+='0.20 0.28 0.38 rg '+center('Se otorga el presente certificado a',430,13,'F3');
  c+='0.05 0.12 0.22 rg '+center(data.name||'',382,28,'F2');
  c+='0.11 0.42 0.70 RG 1.5 w 150 365 m 642 365 l S\n';
  c+='0.20 0.28 0.38 rg '+center('Por haber completado satisfactoriamente',325,13,'F3');
  c+='0.06 0.18 0.32 rg '+center(data.activity||'',286,18,'F2');
  c+='0.18 0.26 0.36 rg '+center(data.result||'',246,13,'F1');
  c+='0.30 0.36 0.44 rg '+center(`Emitido el ${date}`,205,12,'F3');
  c+='0.18 0.25 0.34 RG 1 w 95 120 m 300 120 l S 492 120 m 697 120 l S\n';
  c+='0.18 0.25 0.34 rg '+center('Simulación educativa independiente · No equivale a una certificación oficial',70,10,'F1');
  c+='1 1 1 rg BT /F2 11 Tf 28 18 Td (FORMACION CONTINUA EN QUALITY ASSURANCE) Tj ET\n';
  const objs=[];objs[1]='<< /Type /Catalog /Pages 2 0 R >>';objs[2]='<< /Type /Pages /Kids [3 0 R] /Count 1 >>';objs[3]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 792 612] /Resources << /Font << /F1 5 0 R /F2 6 0 R /F3 7 0 R >> >> /Contents 4 0 R >>';objs[4]=`<< /Length ${c.length} >>\nstream\n${c}endstream`;objs[5]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';objs[6]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';objs[7]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique /Encoding /WinAnsiEncoding >>';let pdf='%PDF-1.4\n',offs=[0];for(let i=1;i<=7;i++){offs[i]=pdf.length;pdf+=`${i} 0 obj\n${objs[i]}\nendobj\n`;}const xref=pdf.length;pdf+='xref\n0 8\n0000000000 65535 f \n';for(let i=1;i<=7;i++)pdf+=String(offs[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer << /Size 8 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const blob=new Blob([pdf],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}
window.downloadStyledCertificatePdf=downloadStyledCertificatePdf;
const voiceBtn=$('#voiceNav'),voiceStatus=$('#voiceStatus');
function sayStatus(text,ms=3500){if(!voiceStatus)return;voiceStatus.textContent=text;voiceStatus.hidden=false;clearTimeout(window.__voiceStatusTimer);window.__voiceStatusTimer=setTimeout(()=>voiceStatus.hidden=true,ms);}
function voiceRoute(text){const t=text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const routes=[[/\b(inicio|home)\b/,'index.html'],[/\b(academia|academy|certificaciones)\b/,'academia.html'],[/\b(simulador|simuladores|examen|practica|practice)\b/,'simuladores.html'],[/\b(cursos|curso tecnico|herramientas|learning path|ruta)\b/,'academia.html#tecnicos'],[/\b(prompts|prompt|inteligencia artificial)\b/,'prompts.html'],[/\b(preguntas frecuentes|faq)\b/,'faq.html'],[/\b(empleo|empleos|trabajo|jobs)\b/,'empleos.html'],[/\b(pago|pagar|inscripcion|payment)\b/,'pago.html'],[/\b(iniciar sesion|login|perfil|sign in)\b/,'login.html']];for(const [rx,url] of routes){if(rx.test(t)){location.href=url;return true;}}if(/modo oscuro|tema oscuro|dark mode/.test(t)){document.body.classList.add('dark');localStorage.setItem('theme','dark');sayStatus('Modo oscuro activado');return true;}if(/modo claro|tema claro|light mode/.test(t)){document.body.classList.remove('dark');localStorage.setItem('theme','light');sayStatus('Modo claro activado');return true;}if(/accesibilidad|accessibility/.test(t)){if($('#accessibilityPanel'))$('#accessibilityPanel').hidden=false;sayStatus('Panel de accesibilidad abierto');return true;}if(/arriba|subir|top/.test(t)){scrollTo({top:0,behavior:'smooth'});sayStatus('Volviendo al inicio de la página');return true;}return false;}
if(voiceBtn){voiceBtn.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){sayStatus('La navegación por voz no está disponible en este navegador.',5000);return;}const r=new SR();const map={es:'es-ES',en:'en-US',pt:'pt-BR',zh:'zh-CN',hi:'hi-IN'};r.lang=map[localStorage.getItem('lang')||'es']||'es-ES';r.interimResults=false;r.maxAlternatives=1;voiceBtn.classList.add('listening');voiceBtn.setAttribute('aria-pressed','true');sayStatus('Escuchando…',7000);r.onresult=e=>{const text=e.results[0][0].transcript;sayStatus('Comando: '+text,4500);if(!voiceRoute(text))setTimeout(()=>sayStatus('No reconocí la sección solicitada.',5000),400);};r.onerror=()=>sayStatus('No fue posible reconocer el comando de voz.',4500);r.onend=()=>{voiceBtn.classList.remove('listening');voiceBtn.setAttribute('aria-pressed','false');};try{r.start();}catch{sayStatus('El reconocimiento de voz ya está activo.');}};}

// v12: botón volver al inicio
(()=>{const b=document.getElementById('backToTop');if(!b)return;const sync=()=>b.classList.toggle('show',window.scrollY>420);window.addEventListener('scroll',sync,{passive:true});b.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));sync();})();
