(function(){
 const btn=document.getElementById('searchQaLinkedIn');if(!btn)return;
 const COUNTRIES={"Americas": ["Antigua and Barbuda", "Argentina", "Bahamas", "Barbados", "Belize", "Bolivia", "Brazil", "Canada", "Chile", "Colombia", "Costa Rica", "Cuba", "Dominica", "Dominican Republic", "Ecuador", "El Salvador", "Grenada", "Guatemala", "Guyana", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Suriname", "Trinidad and Tobago", "United States", "Uruguay", "Venezuela"], "Europe": ["Albania", "Andorra", "Austria", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Holy See (Vatican City)", "Hungary", "Iceland", "Ireland", "Italy", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal", "Romania", "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Ukraine", "United Kingdom"], "Asia": ["Afghanistan", "Armenia", "Azerbaijan", "Bahrain", "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China", "Cyprus", "Georgia", "India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan", "Kazakhstan", "Kuwait", "Kyrgyzstan", "Laos", "Lebanon", "Malaysia", "Maldives", "Mongolia", "Myanmar", "Nepal", "North Korea", "Oman", "Pakistan", "Palestine", "Philippines", "Qatar", "Saudi Arabia", "Singapore", "South Korea", "Sri Lanka", "Syria", "Taiwan", "Tajikistan", "Thailand", "Timor-Leste", "Türkiye", "Turkmenistan", "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen"]};
 const JOBS=[{"title": "QA Engineer CR", "company": "Core Code io", "country": "Costa Rica", "continent": "Americas", "mode": "onsite", "type": "fulltime", "age": "~17 horas", "desc": "QA de software en Alajuela; oportunidad publicada recientemente en LinkedIn.", "url": "https://cr.linkedin.com/jobs/view/qa-engineer-cr-at-core-code-io-4464155224"}, {"title": "Automation QA Engineer CR", "company": "Core Code io", "country": "Costa Rica", "continent": "Americas", "mode": "onsite", "type": "fulltime", "age": "~17 horas", "desc": "Automatización QA y suites de testing; publicación reciente en LinkedIn.", "url": "https://cr.linkedin.com/jobs/view/automation-qa-engineer-cr-at-core-code-io-4464143927"}, {"title": "Application Tester CR", "company": "Core Code io", "country": "Costa Rica", "continent": "Americas", "mode": "onsite", "type": "fulltime", "age": "~1 día", "desc": "Testing de aplicaciones web, móvil y desktop; casos, regresión y defectos.", "url": "https://cr.linkedin.com/jobs/view/application-tester-cr-at-core-code-io-4464147975"}, {"title": "QA Tester", "company": "Unisys", "country": "Costa Rica", "continent": "Americas", "mode": "remote", "type": "fulltime", "age": "~3 días", "desc": "Pruebas funcionales, integración, UAT e incidentes/defectos.", "url": "https://cr.linkedin.com/jobs/view/qa-tester-at-unisys-4464366779"}, {"title": "Quality Assurance Engineer - Trabajo Remoto", "company": "BairesDev", "country": "Costa Rica", "continent": "Americas", "mode": "remote", "type": "fulltime", "age": "~2 días", "desc": "Quality Assurance remoto; listado reciente en LinkedIn Costa Rica.", "url": "https://cr.linkedin.com/jobs/qa-engineer-empleos"}, {"title": "QA Engineer / Test Automation", "company": "Cronos Europa", "country": "Portugal", "continent": "Europe", "mode": "onsite", "type": "fulltime", "age": "vigente en revisión", "desc": "Test automation para programa tecnológico de fabricante automotriz global en Lisboa.", "url": "https://pt.linkedin.com/jobs/view/qa-engineer-test-automation-at-cronos-europa-4458753246"}];
 const continent=document.getElementById('qaJobContinent');
 const country=document.getElementById('qaJobCountry');
 const status=document.getElementById('qaJobSearchStatus');
 const box=document.getElementById('qaJobResults');
 const labels={Americas:'América',Europe:'Europa',Asia:'Asia'};
 function populateCountries(){
   const c=continent.value;
   const selected=country.value;
   const list=c?COUNTRIES[c]:Object.values(COUNTRIES).flat();
   country.innerHTML='<option value="">Todos los países</option>'+[...new Set(list)].sort((a,b)=>a.localeCompare(b,'es')).map(x=>`<option value="${x}">${x}</option>`).join('');
   if([...country.options].some(o=>o.value===selected))country.value=selected;
 }
 function modeText(v){return v==='remote'?'Remoto':v==='hybrid'?'Híbrido':'Presencial'}
 function typeText(v){return v==='internship'?'Internship / pasantía':v==='contract'?'Contrato':'Tiempo completo'}
 function filters(){return {continent:continent.value,country:country.value,workplace:document.getElementById('qaJobWorkplace').value,type:document.getElementById('qaJobType').value,keyword:(document.getElementById('qaJobKeyword').value||'Quality Assurance').trim()}}
 let page=1,hasNext=false;const pager=document.getElementById('qaJobPagination'),prev=document.getElementById('qaJobPrev'),next=document.getElementById('qaJobNext'),pageLabel=document.getElementById('qaJobPageLabel');
 function renderFallback(){const f=filters(),kw=f.keyword.toLowerCase();const list=JOBS.filter(j=>(!kw||(`${j.title} ${j.company} ${j.desc}`.toLowerCase().includes(kw)||kw==='quality assurance'||kw==='qa'))&&(!f.continent||j.continent===f.continent)&&(!f.country||j.country===f.country)&&(!f.workplace||j.mode===f.workplace)&&(!f.type||j.type===f.type));box.innerHTML=list.map(j=>`<article class="job-opportunity"><div class="job-card-top"><span class="badge">Catálogo verificado</span><span class="job-age">${j.age}</span></div><h3>${j.title}</h3><p><strong>${j.company}</strong> · ${j.country}</p><p>${j.desc}</p><div class="card-actions"><a class="btn secondary small" href="${j.url}" target="_blank" rel="noopener noreferrer">Ver publicación ↗</a></div></article>`).join('')||'<div class="empty-state"><h3>Sin resultados</h3></div>';if(pager)pager.hidden=true;}
 async function render(reset=true){if(reset)page=1;status.hidden=false;status.textContent='Buscando oportunidades QA…';box.innerHTML='';try{const q=new URLSearchParams({...filters(),page});const r=await fetch('/api/search-jobs?'+q),data=await r.json();if(!r.ok)throw new Error();box.innerHTML=(data.items||[]).map(j=>`<article class="job-opportunity"><div class="job-card-top"><span class="badge">${j.source}</span></div><h3>${escapeHtml(j.title)}</h3><p>${escapeHtml(j.snippet||'')}</p><a class="btn secondary small" href="${j.link}" target="_blank" rel="noopener noreferrer">Ver publicación ↗</a></article>`).join('');hasNext=!!data.hasNext;pager.hidden=false;pageLabel.textContent=`Página ${page}`;prev.disabled=page<=1;next.disabled=!hasNext;status.textContent=`${data.items?.length||0} resultados encontrados.`;}catch(e){renderFallback();status.textContent=box.querySelector('.job-opportunity')?'Resultados disponibles para los filtros seleccionados.':'No se encontraron resultados con estos filtros.';}}
 continent.addEventListener('change',()=>{populateCountries();box.innerHTML='';status.hidden=true;});
 btn.addEventListener('click',()=>render(true));
 prev?.addEventListener('click',()=>{if(page>1){page--;render(false)}});next?.addEventListener('click',()=>{if(hasNext){page++;render(false)}});
 document.getElementById('qaJobKeyword')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();render(true);}});
 populateCountries();
 box.innerHTML='';status.hidden=true;

 document.querySelectorAll('.employment-nav a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{
   e.preventDefault();const target=document.querySelector(a.getAttribute('href'));if(!target)return;
   target.scrollIntoView({behavior:'smooth',block:'start'});
   history.replaceState(null,'',a.getAttribute('href'));
 }));
})();