const WTASKS=[
{l:'A1',min:25,p:'Introduce yourself. Write where you live, what you do, and two things you like.',g:'Use simple sentences and familiar vocabulary.'},
{l:'A2',min:50,p:'Write a short message to a friend describing your weekend plans and explain why you chose them.',g:'Connect ideas with and, but, because, then.'},
{l:'B1',min:90,p:'Describe an experience that taught you something important. Explain what happened, how you felt, and what you learned.',g:'Use connected paragraphs and give reasons.'},
{l:'B2',min:140,p:'Should companies allow employees to work remotely? Discuss advantages and disadvantages and give your opinion.',g:'Organize an argument with examples and contrasting ideas.'},
{l:'C1',min:190,p:'Write a structured response on how technology changes the way people learn. Evaluate benefits, limitations, and conditions for effective use.',g:'Develop a clear position, support it, and conclude appropriately.'},
{l:'C2',min:240,p:'“Efficiency and human judgment are often presented as opposites.” Write a nuanced essay challenging or defending this claim, addressing assumptions and counterarguments.',g:'Use precise language, subtle distinctions, cohesive argumentation, and an appropriate register.'}
];
let wi=0,wans=Array(WTASKS.length).fill('');
const connectors={A1:['and'],A2:['and','but','because','then'],B1:['because','however','although','so','when','while'],B2:['however','although','whereas','therefore','on the other hand','for example'],C1:['nevertheless','consequently','furthermore','in contrast','provided that','despite'],C2:['notwithstanding','arguably','albeit','inasmuch as','by contrast','to the extent that']};
function wc(t){return (t.trim().match(/\b[\w'-]+\b/g)||[]).length}function uniq(t){const a=(t.toLowerCase().match(/\b[a-z']+\b/g)||[]);return a.length?new Set(a).size/a.length:0}function features(t,task){const words=wc(t),sent=(t.match(/[.!?]+/g)||[]).length,paras=t.split(/\n\s*\n/).filter(x=>x.trim()).length,low=t.toLowerCase();const conn=Object.values(connectors).flat().filter(x=>low.includes(x)).length;let score=0;score+=Math.min(45,words/task.min*45);score+=Math.min(20,sent>=3?12+Math.min(8,sent):sent*4);score+=Math.min(15,uniq(t)*25);score+=Math.min(15,conn*3);score+=paras>=2?5:0;return Math.round(Math.min(100,score))}
function renderW(){const t=WTASKS[wi];writingProgress.textContent=`Tarea ${wi+1} / ${WTASKS.length}`;writingBand.textContent=t.l;writingPrompt.textContent=t.p;writingGuidance.textContent=t.g;writingText.value=wans[wi];writingTarget.textContent=`Target: ~${t.min}+ words`;writingWords.textContent=`${wc(wans[wi])} words`;writingPrev.disabled=wi===0;writingNext.textContent=wi===WTASKS.length-1?'Ver resultado':'Siguiente →'}
function finishW(){const scores=WTASKS.map((t,i)=>features(wans[i],t));let level='A1';for(let i=0;i<scores.length;i++){if(scores[i]>=65)level=WTASKS[i].l;else break}writingLevel.textContent=`Writing estimado: ${level}`;writingSummary.textContent='Estimación educativa basada en indicadores formales de producción escrita; no equivale a una calificación oficial MCER.';writingBreakdown.innerHTML=WTASKS.map((t,i)=>`<div class="score-card"><strong>${t.l}</strong><span>${scores[i]}%</span><div class="mini-bar"><i style="width:${scores[i]}%"></i></div></div>`).join('');writingFeedback.innerHTML=WTASKS.map((t,i)=>{const words=wc(wans[i]);return `<article class="review-mistake"><span class="badge">${t.l}</span><h3>${t.p}</h3><p><b>Words:</b> ${words} / target ${t.min}+</p><p><b>Consejo:</b> ${scores[i]>=65?'La respuesta muestra suficiente desarrollo para esta práctica. Revise gramática y precisión con una persona o docente.':'Amplíe ideas, conecte oraciones y agregue razones/ejemplos antes de avanzar al siguiente nivel.'}</p></article>`}).join('');writingQuiz.hidden=true;writingResult.hidden=false;writingResult.scrollIntoView({behavior:'smooth'})}
startWriting.onclick=()=>{wi=0;wans=Array(WTASKS.length).fill('');writingStart.hidden=true;writingResult.hidden=true;writingQuiz.hidden=false;renderW()};writingText.oninput=()=>{wans[wi]=writingText.value;writingWords.textContent=`${wc(wans[wi])} words`};writingPrev.onclick=()=>{wans[wi]=writingText.value;if(wi>0){wi--;renderW()}};writingNext.onclick=()=>{wans[wi]=writingText.value;if(wi===WTASKS.length-1)finishW();else{wi++;renderW()}};writingRetry.onclick=()=>{writingResult.hidden=true;writingStart.hidden=false};