(function(){
 const level=document.getElementById('jobLevel'),button=document.getElementById('linkedinJobSearch');
 const terms={jr:'Junior QA / QA Tester',mid:'QA Engineer / QA Analyst',sr:'Senior QA / Senior QA Engineer',lead:'QA Lead / Test Lead'};
 if(level&&button){button.removeAttribute('href');button.removeAttribute('target');button.setAttribute('role','button');button.addEventListener('click',e=>{e.preventDefault();const guide=document.querySelector('.linkedin-guide');if(guide){guide.innerHTML=`<strong>Búsqueda preparada: ${terms[level.value]}</strong><p>Revise oportunidades en la sección <a href="#linkedin-reciente">LinkedIn · oportunidades recientes</a>. Puede combinar este nivel con país, modalidad, tipo de empleo y palabra clave sin salir de esta página.</p>`;guide.scrollIntoView({behavior:'smooth',block:'nearest'});}});}
})();
const GAME_COMMUNITIES=[
 ['america','Costa Rica','IGDA Costa Rica'],['america','Argentina','IGDA Argentina'],['america','Brasil · São Paulo','IGDA São Paulo'],['america','Brasil · Campinas','IGDA Campinas'],['america','Brasil · Fortaleza','IGDA Fortaleza'],['america','Chile','IGDA Chile'],['america','Colombia','IGDA Colombia'],['america','Guatemala','IGDA Guatemala'],['america','México · Sur','IGDA México Sur'],['america','México · Norte','IGDA Northern México'],['america','Paraguay','IGDA Paraguay'],['america','Canadá · Vancouver','IGDA Vancouver'],['america','Canadá · Toronto','IGDA Toronto'],['america','EE. UU. · Los Angeles','IGDA Los Angeles'],['america','EE. UU. · San Francisco','IGDA San Francisco'],['america','EE. UU. · Silicon Valley','IGDA Silicon Valley'],['america','EE. UU. · Austin','IGDA Austin'],['america','EE. UU. · New York','IGDA New York City'],['america','EE. UU. · Boston','IGDA Boston'],
 ['europe','Alemania · Berlín','IGDA Berlin'],['europe','Dinamarca','IGDA Denmark'],['europe','Estonia','IGDA Estonia'],['europe','Finlandia','IGDA Finland'],['europe','Grecia','IGDA Greece'],['europe','Italia','IGDA Italy'],['europe','Portugal','IGDA Portugal'],['europe','Suecia','IGDA Sweden'],['europe','Suiza','IGDA Switzerland'],['europe','Reino Unido · Londres','IGDA London'],['europe','Turquía · Estambul','IGDA Istanbul'],['europe','Ucrania · Kyiv','IGDA Kyiv'],['europe','Bulgaria','IGDA Bulgaria'],
 ['asia','India','IGDA India'],['asia','Japón','IGDA Japan'],['asia','China · Shenzhen','IGDA Shenzhen'],['asia','Indonesia','IGDA Indonesia'],['asia','Malasia','IGDA Malaysia'],['asia','Filipinas · Manila','IGDA Manila'],['asia','Singapur','IGDA Singapore'],['asia','Taiwán','IGDA Taiwan'],['asia','Vietnam','IGDA Vietnam'],['asia','Sri Lanka','IGDA Sri Lanka'],['asia','Australia · Sydney','IGDA Sydney'],['asia','Australia · Melbourne','IGDA Melbourne'],['asia','Australia · Brisbane','IGDA Brisbane']
];
(function(){const grid=document.getElementById('gameCommunityGrid'),region=document.getElementById('gameRegionFilter'),search=document.getElementById('gameCommunitySearch');if(!grid)return;const render=()=>{const r=region?.value||'all',q=(search?.value||'').toLowerCase().trim();const items=GAME_COMMUNITIES.filter(x=>(r==='all'||x[0]===r)&&(!q||(x[1]+' '+x[2]).toLowerCase().includes(q)));grid.innerHTML=items.map(x=>`<article data-region="${x[0]}"><span class="badge">${x[1]}</span><h3>${x[2]}</h3><p>Comunidad profesional de desarrollo de videojuegos. Úsela para networking, eventos y exploración de oportunidades relacionadas con QA.</p><a class="btn ghost small" href="https://igda.org/chapters/" target="_blank" rel="noopener noreferrer">Ver directorio IGDA ↗</a></article>`).join('')||'<p>No se encontraron comunidades con esos filtros.</p>';window.applyTranslations?.();};region?.addEventListener('change',render);search?.addEventListener('input',render);render();})();
